---
title: "p8105_hw6_zx2231_tc2900"
author: "Chen Shaoxuan"
date: "11/14/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(ggthemes)
library(ggridges)
```

```{r}
noaa = read_csv("./data/nynoaadat.zip")%>% 
  clean_names()
```

#Make the bar plot of the missing value of snow.
```{r}
noaa %>%
  mutate(tmax = as.numeric(tmax),
         tmin = as.numeric(tmin)) %>% 
  mutate(t_range = tmax-tmin) %>% 
  group_by(id) %>%
  summarise(t_range_max = max(t_range)) %>% 
  plot_ly(x = ~id, y = ~t_range_max, color = ~id, colors = "Set1",
       type = "bar" )
```

#make a box plot showing the distribution of snowfall <200 for each year
```{r}
noaa %>% 
   separate(date, into = c("year", "month", "day"), sep = "-") %>% 
   filter(snow < 200 & snow > 0) %>% 
  plot_ly(x = ~year, y = ~snow, color = ~year,
          colors = "Set1",                                       
          type = "box") 
```

#make a scatterplot of the snow depth of station USC00309516.
```{r}

```

