---
title: "p8105_hw6_zx2231_tc2900_dashboard"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)

library(plotly)
```

```{r}
noaa = read_csv("./data/nynoaadat.zip")%>% 
  clean_names()
```

### Chart 1
    
```{r}
noaa %>%
  mutate(tmax = as.numeric(tmax),
         tmin = as.numeric(tmin)) %>% 
  mutate(t_range = tmax-tmin) %>% 
  group_by(id) %>%
  summarise(t_range_max = max(t_range)) %>% 
  plot_ly(x = ~id, y = ~t_range_max, color = ~id, colors = "Set1",
       type = "bar" )
```
    
### Chart 2

```{r}
noaa %>% 
   separate(date, into = c("year", "month", "day"), sep = "-") %>% 
   filter(snow < 200 & snow > 0) %>% 
  plot_ly(x = ~year, y = ~snow, color = ~year,
          colors = "Set1",                                       
          type = "box") 
```

### Chart 3

```{r}
noaa %>% 
   separate(date, into = c("year", "month", "day"), sep = "-") %>% 
   filter(id == "USC00309516") %>% 
   filter(snwd < 2000 & snwd > 0) %>%  
   filter(snow < 3000 & snow > 0) %>% 
   mutate(hover_text = str_c("Precipitation(tenths of mm):", prcp)) %>%  
  plot_ly(x = ~snow, y = ~snwd, color = ~year,
          text = ~hover_text,
          colors = "Set1",                                       
          type = "scatter",  alpha = 0.5)  
```




